cameras:
  - id: charles_bridge
    name: Charles Bridge
    lat: 50.0865
    lon: 14.4119
    source: https://bezpecnost.praha.eu/Intens.CrisisPortalInfrastructureApp/cameras/101200/image
  - id: hybernska
    name: Hybernská
    lat: 50.0875
    lon: 14.4316
    source: https://bezpecnost.praha.eu/Intens.CrisisPortalInfrastructureApp/cameras/101048/image
  - id: jecna
    name: Jecná
    lat: 50.0754
    lon: 14.4378
    source: https://bezpecnost.praha.eu/Intens.CrisisPortalInfrastructureApp/cameras/202020/image
tools:
  internet: false
  weather: false
  maps: false
